# Generated by Django 3.1.1 on 2020-10-16 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201016_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Purchase_Date'),
            preserve_default=False,
        ),
    ]
