# Generated by Django 3.1.1 on 2020-12-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201214_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Purchase_Date'),
        ),
    ]
