# Generated by Django 3.1.1 on 2021-01-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201214_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='last_name',
        ),
        migrations.AddField(
            model_name='details',
            name='contact',
            field=models.CharField(blank=True, max_length=13, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='details',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='male', max_length=9),
        ),
    ]
