# Generated by Django 2.2.4 on 2020-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0002_auto_20200421_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='endtime',
            field=models.TimeField(blank=True, help_text='Tournment end time is on ..', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='leave',
            name='starttime',
            field=models.TimeField(blank=True, help_text='Tournment start time is on ..', null=True, verbose_name='Start Time'),
        ),
    ]
