# Generated by Django 2.2.4 on 2020-04-21 12:39

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0003_auto_20200421_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
