# Generated by Django 2.2.4 on 2020-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0005_heats_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
