# Generated by Django 2.2.4 on 2020-04-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0006_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
