# Generated by Django 2.1.7 on 2020-05-14 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0007_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='COUNTRY_RATING',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='COUNTRY RATING'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='players',
            name='title',
            field=models.CharField(choices=[('Women GM', 'Women GM'), ('International Master', 'International Master'), ('WOMEN IM', 'WOMEN_IM'), ('FIDE M', 'FIDE_M'), ('Women FIDE M', 'Women_FIDE_M'), ('CM', 'CM'), ('Women CM', 'Women_CM'), ('National Master', 'National_Master'), ('W N M', 'W_N_M')], default='Women GM', max_length=8, verbose_name='Title'),
        ),
    ]
