# Generated by Django 3.1.1 on 2020-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0008_auto_20200514_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='male', max_length=9, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='players',
            name='title',
            field=models.CharField(choices=[('Women GM', 'Women GM'), ('International Master', 'International Master'), ('WOMEN IM', 'WOMEN_IM'), ('FIDE M', 'FIDE_M'), ('Women FIDE M', 'Women_FIDE_M'), ('CM', 'CM'), ('Women CM', 'Women_CM'), ('National Master', 'National_Master'), ('W N M', 'W_N_M')], default='Women GM', max_length=20, verbose_name='Title'),
        ),
    ]
