# Generated by Django 3.1.4 on 2020-12-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0009_auto_20201015_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='tournment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournment.leave'),
        ),
    ]
