# Generated by Django 3.1.4 on 2020-12-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0010_players_tournment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='games',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rounds',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournment.leave'),
        ),
    ]
