# Generated by Django 3.1.1 on 2020-12-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0011_auto_20201215_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='loc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='PGN File Location'),
        ),
    ]
